### ISSUE TITLE
Feature request: Smooth scroll

### ISSUE THREAD

**Issue by Ampa** [lijyze/scroll-offset#2]
I am trying your plugin, and prefer it to the similar Typewriter Scroll.

I find it a little jarring when I start to type and the text suddenly jumps to the specified position.
Is it possible to smoothly scroll, over a period of perhaps a few seconds, to the new position?
That way my eyes will more easily follow the movement!

Thanks for the plugin.

**Comment by lijyze** [comment]
I have thought about this feature when I write this plugin, but I abandon this idea at last, and this thought never come back to my mind when I writing with the plugin. After seeing this issue, I thought it over again.

The purpose of this plugin is to allow users to have an eye on the context, rather than the 'scroll'. Besides, if the 'a period of time' is short, It's behavior will be just like 'jump'. But if it is long, It will really break input experience. No mention to the difference of scroll distance make it hard to keep the consistency of the function.
